export const mockArticles = [
  {
    id: "art-001",
    title: "THE GREAT BIFURCATION: DEBT CYCLES AND DOMINANT RESERVE VECTORS",
    description: "An analysis of the structural divergence in global debt structures and the shifting gravity of reserve asset dynamics in the post-inflationary epoch.",
    content: "The global monetary framework is fracturing along predictable lines. As central banks navigate the tail-end of the post-pandemic credit expansion, a stark divergence has emerged between sovereign debt markets. This paper examines the systemic forces driving capital reallocation toward decentralized and regional reserve vectors, modeling the transition away from unipolar dollar hegemony. Through historical comparison with the late-stage Bretton Woods transition, we demonstrate how contemporary trade bilateralism acts as a catalytic agent for structural interest rate volatility. The implications for institutional capital are profound: liquidity is no longer a neutral utility, but a contested political space. We project that over the next decade, sovereign asset allocation will shift increasingly into non-aligned digital reserves and physical commodities, forcing a permanent repricing of risk premium across G10 bond markets.",
    publishedAt: "2026-06-30T10:00:00Z",
    sourceName: "NewForm Quarterly",
    category: "Macroeconomics",
    readTime: "12 min read",
    author: "Helena Vance",
    urlToImage: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 1.0,
      'AI Frontiers': 0.0,
      Architecture: 0.0,
      Geopolitics: 0.4,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.1,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-002",
    title: "NEURAL COGNITION PATHWAYS: BEYOND THE TRANSFORMER BOTTLENECK",
    description: "Investigating state-space models and physical compute topologies designed to supersede attention-based learning systems.",
    content: "For a decade, the Transformer architecture has stood as the undisputed foundation of artificial intelligence. Yet, as we approach physical limits of silicon scaling and compute-density costs, the attention mechanism's quadratic complexity looms as an insuperable wall. This report details the emergence of linear-time sequence models—specifically Mamba and state-space neural networks—which operate with constant memory scaling. By examining how biological systems process temporal sequences, researchers are designing hardware-aware network topologies that approximate real-time human cognition without massive power budgets. The shift from data-brute-forcing to structural efficiency represents the next paradigm of cognitive computation. We analyze the investment velocity in custom non-von Neumann silicon and project the timeline for the first fully autonomous edge-intelligence systems capable of self-directed logical induction.",
    publishedAt: "2026-06-29T14:30:00Z",
    sourceName: "The Broadside Journal",
    category: "AI Frontiers",
    readTime: "9 min read",
    author: "Dr. Kaelen Thorne",
    urlToImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.2,
      'AI Frontiers': 1.0,
      Architecture: 0.0,
      Geopolitics: 0.1,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.6,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.0,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-003",
    title: "BRUTALIST MONUMENTS AND THE APOCALYPSE OF EXTRUDED MONOLITHS",
    description: "A spatial study of mid-century concrete forms and their relevance to contemporary architectural resilience in volatile climates.",
    content: "The brutalist movement of the 1960s was more than an aesthetic provocation; it was a socio-political response to the fragility of post-war reconstruction. Today, as climate volatility threatens contemporary glass-and-steel typologies, the thermal mass and structural permanence of raw concrete (béton brut) demand re-evaluation. This architectural critique surveys the durability of structural monoliths across Northern Europe and East Asia, arguing that concrete's heavy thermal inertia provides an involuntary carbon-offsetting blueprint for passive heating and cooling. By rejecting superficial facades, brutalism exposes the load-bearing truth of architectural spaces. We examine how contemporary designers are marrying this tectonic honesty with low-carbon pozzolanic cements to create new forms of defensive, resilient civic infrastructure that can survive centuries of environmental stress.",
    publishedAt: "2026-06-28T09:15:00Z",
    sourceName: "Hypatia Dispatch",
    category: "Architecture",
    readTime: "7 min read",
    author: "Evelyn Sterling",
    urlToImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.1,
      'AI Frontiers': 0.0,
      Architecture: 1.0,
      Geopolitics: 0.2,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.5,
      'Climate Futures': 0.4,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-004",
    title: "THE STRATEGIC CHOKEPOINTS: WATERWAY SOVEREIGNTY AND PROXY BLOCKADES",
    description: "Mapping naval deployment vectors and trade vulnerabilities in critical maritime corridors.",
    content: "Over ninety percent of global volume trade passes through a handful of narrow sea lanes. These chokepoint channels—the Straits of Malacca, the Suez Canal, and the Bab-el-Mandeb—have become the primary levers of asymmetrical geopolitical conflict. In this paper, we map the density of naval deployments and proxy skirmishes that threaten to disrupt merchant shipping. As non-state actors acquire precision guided strike capabilities at scale, the cost of securing maritime trade routes has risen exponentially. We argue that the traditional doctrine of open-sea passage is being replaced by localized protectionist umbrellas, forcing cargo carriers to consider long-term overland alternatives. The economic fallout of a prolonged blockade in any key channel will trigger immediate inflationary impulses across global supply networks, rendering current just-in-time inventory models obsolete.",
    publishedAt: "2026-06-27T16:45:00Z",
    sourceName: "Zürich Review",
    category: "Geopolitics",
    readTime: "11 min read",
    author: "Marcus Finch",
    urlToImage: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.5,
      'AI Frontiers': 0.0,
      Architecture: 0.0,
      Geopolitics: 1.0,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.1,
      'Astra-Exploration': 0.4
    }
  },
  {
    id: "art-005",
    title: "THE DECAY OF THE AVATAR: HYPER-PERSONALITY AND THE HOLLOW CELEBRITY ICON",
    description: "Analyzing how virtual celebrity avatars are replacing physical stars, collapsing the boundaries between celebrity culture, fandom vectors, and AI agents.",
    content: "The age of the biological superstar is drawing to a close. As deep generative pipelines reach absolute fidelity, talent agencies are transitioning to virtual IP portfolios—synthesized avatars that never age, break contracts, or engage in unscripted controversies. This socio-cultural critique charts the rise of virtual pop icons and algorithmically managed celebrities. By leveraging real-time telemetry from millions of listeners, these digital avatars adjust their vocal timbre, visual aesthetic, and behavioral traits to match localized demographic desires. The result is a perfect, feedback-looped commodity. Fandom is no longer a relationship between a spectator and a human artist, but an interactive vector model of parasocial optimization. We examine the economic structures of digital asset holding companies and project the implications for human creatives in a market dominated by synthetic, corporate-owned personas.",
    publishedAt: "2026-06-26T18:00:00Z",
    sourceName: "Broadside Culture Journal",
    category: "Pop Culture & Celebs",
    readTime: "10 min read",
    author: "Amara Cole",
    urlToImage: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.3,
      'AI Frontiers': 0.6,
      Architecture: 0.0,
      Geopolitics: 0.0,
      'Pop Culture & Celebs': 1.0,
      'Avant-Garde Music': 0.5,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.0,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-006",
    title: "RESONANCE IN SILENCE: COMPOSITIONAL ENTROPY AND THE DESTRUCTION OF THE CHORD",
    description: "A study of experimental microtonality, generative noise patches, and spatialized synthesis methods reshaping the sonic underground.",
    content: "Standard 12-tone equal temperament is a historical constraint, not an acoustic necessity. In the global musical underground, a quiet rebellion is taking place as composers discard western harmony in favor of pure frequency ratios and chaotic noise synthesis. This composition survey maps the development of spatialized microtonal systems that exploit the physical resonance of performance spaces. Using custom modular synthesizers and mathematical frequency dividers, these artists build long-form droning landscapes that interact directly with the listener's otic biology. We demonstrate how this movement rejects commercial structures—opting for unindexed tape runs and local physical broadcasts—to construct a clean sonic space resistant to algorithmic classification.",
    publishedAt: "2026-06-25T11:40:00Z",
    sourceName: "Decibel Vanguard",
    category: "Avant-Garde Music",
    readTime: "8 min read",
    author: "Zev Larsson",
    urlToImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.0,
      'AI Frontiers': 0.2,
      Architecture: 0.1,
      Geopolitics: 0.0,
      'Pop Culture & Celebs': 0.4,
      'Avant-Garde Music': 1.0,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.0,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-007",
    title: "COHERENCE TIME EXTENSION: THE SPIN-QUBIT MONOPOLY IN VALENCE BANDS",
    description: "Deep-dive report on cryogenically stabilized spin qubits and the race to achieve fault-tolerant logical compute steps before the decade's end.",
    content: "Quantum computing is emerging from its theoretical childhood. While superconducting circuits remain highly sensitive to thermal noise, spin qubits embedded in silicon-germanium heterostructures have demonstrated coherence times extending into seconds at millikelvin temperatures. This engineering analysis details the manufacturing methods used to isolate single valence electrons and manipulate their spin states via microwave pulses. The bottleneck is no longer qubit fidelity, but interconnect density. We map the venture capital flows into localized cryogenic control chip designs and project when the first commercially viable logical qubits will begin superseding classical supercomputing clusters in structural molecular simulation.",
    publishedAt: "2026-06-24T09:00:00Z",
    sourceName: "Silicon Vector",
    category: "Quantum Computing",
    readTime: "11 min read",
    author: "Dr. Lana Vane",
    urlToImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.4,
      'AI Frontiers': 0.8,
      Architecture: 0.0,
      Geopolitics: 0.2,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 1.0,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.0,
      'Astra-Exploration': 0.3
    }
  },
  {
    id: "art-008",
    title: "DEEP CITY STRATA: THE TECTONICS OF HIGH-DENSITY UNDERGROUND CIVIC NETWORKS",
    description: "Evaluating the construction of secondary metropolitan grids directly into geological foundations to preserve historical surface landscapes.",
    content: "As surface temperatures escalate and historic cities struggle with population density, architects are looking down. By boring directly into granite and basalt shields, urban planners in cities like Seoul and Montreal are constructing massive, multi-tiered subterranean civic environments. This tectonic survey details the engineering challenges of underground vertical shafts, seismic reinforcement, and artificial solar replication. We argue that deep subterranean urbanism is the only viable path to expanding metropolitan capacity without destroying cultural above-ground monuments. The cost of excavation remains monumental, but the long-term energy savings from geo-thermal climate stabilization make subterranean housing blocks highly competitive.",
    publishedAt: "2026-06-23T14:15:00Z",
    sourceName: "Tectonic Forum",
    category: "Subterranean Urbanism",
    readTime: "8 min read",
    author: "Kenji Sato",
    urlToImage: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.3,
      'AI Frontiers': 0.0,
      Architecture: 0.8,
      Geopolitics: 0.0,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 1.0,
      'Climate Futures': 0.5,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-009",
    title: "THE CARBON DRAWDOWN DELUSION: GEOTHERMAL VENTING VS. UPPER-ATMOSPHERE AEROSOLS",
    description: "An engineering critique of geoengineering vectors, analyzing localized acid rain trade-offs against planetary cooling parameters.",
    content: "Planetary temperature management has ceased to be a future scenario; it is an active geopolitical tool. As nations deploy sulfate aerosols into the stratosphere to artificially reflect solar radiation, neighboring countries are experiencing disrupted precipitation regimes. This climate policy paper assesses the conflict potential of uncoordinated solar radiation modification (SRM). Through computer modeling, we show how sulfur-injection programs reduce global temperatures but trigger immediate localized drought across sub-Saharan agricultural zones. We propose a multilateral licensing framework for planetary cooling vectors, demonstrating that unilaterally managed atmospheres will inevitably lead to localized food security crises and legal retaliation.",
    publishedAt: "2026-06-22T08:00:00Z",
    sourceName: "NewForm Quarterly",
    category: "Climate Futures",
    readTime: "13 min read",
    author: "Helena Vance",
    urlToImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.6,
      'AI Frontiers': 0.0,
      Architecture: 0.0,
      Geopolitics: 0.5,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.1,
      'Climate Futures': 1.0,
      'Astra-Exploration': 0.1
    }
  },
  {
    id: "art-010",
    title: "HELIOPAUSE PROBES AND THE COLONIZATION OF LAGRANGIAN L4 ECOSYSTEMS",
    description: "Evaluating custom electromagnetic propulsion loops and closed-loop hydroponics required to anchor manufacturing orbits.",
    content: "Industrial extraction is leaving Earth's gravity well. In the quiet zone between Earth and Moon gravity fields, public and private consortia are positioning the first generation of orbital refining factories. This aerospace survey maps the infrastructure needed to maintain stable manufacturing orbits at the L4 and L5 Lagrange coordinates. By using solar-powered electromagnetic thrusters and recycled asteroid slag, these factories can process raw metal ore without atmosphere drag or local ecological damage. We analyze the treaty configurations governing orbital mineral claims and project that within twenty years, heavy metal extraction will occur entirely off-world, reducing terrestrial pollution footprints by up to sixty percent.",
    publishedAt: "2026-06-21T16:30:00Z",
    sourceName: "Astra Tech Dispatch",
    category: "Astra-Exploration",
    readTime: "14 min read",
    author: "Dr. Vance Vance",
    urlToImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.4,
      'AI Frontiers': 0.3,
      Architecture: 0.0,
      Geopolitics: 0.7,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.2,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.1,
      'Astra-Exploration': 1.0
    }
  },
  {
    id: "art-011",
    title: "TIKTOK DECONSTRUCTION: SHORT-FORM COGNITION AND THE DEATH OF THE ALBUM",
    description: "How 15-second loop algorithms have permanently rewired musical compositions and pop star selection systems.",
    content: "The 3-minute pop song is now too long. Under the dominance of short-form video algorithms, musical compositions are written specifically to go viral in 15-second hooks. This media study examines the structural changes in pop music writing, showing how traditional structures like bridges and verse-chorus transitions are discarded in favor of loopable dynamic peaks. Furthermore, record labels no longer discover talent through musical dedication, but by scraping trend analytics. The result is the rise of micro-celebrities who serve as temporary vessels for viral sounds, only to be discarded when the algorithm shifts attention. We project that this short-form rewiring will lead to a hyper-fragmentation of culture, where communal musical movements are replaced by individualized sonic feeds.",
    publishedAt: "2026-06-20T10:15:00Z",
    sourceName: "Broadside Culture Journal",
    category: "Pop Culture & Celebs",
    readTime: "9 min read",
    author: "Amara Cole",
    urlToImage: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.2,
      'AI Frontiers': 0.4,
      Architecture: 0.0,
      Geopolitics: 0.0,
      'Pop Culture & Celebs': 1.0,
      'Avant-Garde Music': 0.8,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.0,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-012",
    title: "THE SOUND OF ALGORITHMS: NEURAL ACOUSTIC MODELING IN ELECTRONIC SONICS",
    description: "Analyzing the software tools that translate physiological heart rates and focus waves into generative synth sounds.",
    content: "Generative electronic music is adapting to the listener's body in real-time. By connecting biometric sensors (smartwatches, heart-rate monitors) directly to soft synths, artists are composing tracks that modulate tempo, filter cutoff, and envelope times based on biological feedback. This report surveys the open-source software libraries driving this transition, modeling how dynamic soundscapes reduce stress levels or boost focus times during cognitive tasks. The challenge lies in distributing these interactive tracks across traditional platforms, driving the creation of bespoke web players that can capture and calculate sensor inputs locally.",
    publishedAt: "2026-06-19T13:00:00Z",
    sourceName: "Decibel Vanguard",
    category: "Avant-Garde Music",
    readTime: "7 min read",
    author: "Zev Larsson",
    urlToImage: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.0,
      'AI Frontiers': 0.5,
      Architecture: 0.0,
      Geopolitics: 0.0,
      'Pop Culture & Celebs': 0.3,
      'Avant-Garde Music': 1.0,
      'Quantum Computing': 0.2,
      'Subterranean Urbanism': 0.0,
      'Climate Futures': 0.0,
      'Astra-Exploration': 0.0
    }
  },
  {
    id: "art-013",
    title: "THE CRYOGENIC COLOSSUS: THERMAL MASS AND CRYSTAL CHOKEPOINTS",
    description: "A look inside the deep-sea quantum arrays buried under ocean trenches to preserve absolute thermal coherence.",
    content: "To shield qubits from atmospheric radiation and electromagnetic interference, tech consortiums are submerging quantum servers into deep ocean trenches. The freezing, high-pressure environments of the Mariana Trench provide natural insulation, reducing cooling power budgets by up to seventy percent. This structural survey explores the mechanical casing, fiber-optic link vectors, and geopolitical claims surrounding underwater quantum nodes. As state actors race to tap these lines, securing oceanic cabling has become the primary naval defense concern of the digital age.",
    publishedAt: "2026-06-18T16:00:00Z",
    sourceName: "Silicon Vector",
    category: "Quantum Computing",
    readTime: "12 min read",
    author: "Dr. Lana Vane",
    urlToImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.3,
      'AI Frontiers': 0.6,
      Architecture: 0.0,
      Geopolitics: 0.6,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 1.0,
      'Subterranean Urbanism': 0.2,
      'Climate Futures': 0.1,
      'Astra-Exploration': 0.2
    }
  },
  {
    id: "art-014",
    title: "RECONSTRUCTING GLACIAL BASINS: GEOTHERMAL DEFLECTORS IN WEST ANTARCTICA",
    description: "Evaluating thermal barriers built along ice sheet base vectors to prevent structural collapse and sea rise.",
    content: "The Thwaites Glacier is melting from the bottom up, driven by geothermal heat currents under the Antarctic shelf. This engineering review analyzes a proposal to install massive, seawater-cooled thermal deflection grids directly at the grounding line of the glacier. By cooling the rock face, engineers hope to slow ice slippage rates by up to forty percent over the next fifty years. We discuss the astronomical capital requirements, international funding vectors, and the legal questions surrounding geoengineering projects on non-sovereign continental shelves.",
    publishedAt: "2026-06-17T09:40:00Z",
    sourceName: "Tectonic Forum",
    category: "Climate Futures",
    readTime: "10 min read",
    author: "Kenji Sato",
    urlToImage: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop",
    vectorWeights: {
      Macroeconomics: 0.5,
      'AI Frontiers': 0.1,
      Architecture: 0.3,
      Geopolitics: 0.2,
      'Pop Culture & Celebs': 0.0,
      'Avant-Garde Music': 0.0,
      'Quantum Computing': 0.0,
      'Subterranean Urbanism': 0.2,
      'Climate Futures': 1.0,
      'Astra-Exploration': 0.0
    }
  }
];
